Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.hostname = "mwsu-schedule-api.prod"
  config.vm.provision "shell", path: "flask-env.sh", privileged: false

  
  config.vm.network "forwarded_port", guest: 80, host: 3000, id: "flask", protocol: "tcp", auto_correct: true
end
